### PR TITLE
Update 31_card_docs_update.sql doc about a style added

### PR DESCRIPTION
**Pull request by amrutadotorg**

### CODE REVIEW

**Review by lovasoa — CHANGES_REQUESTED** [review]
It looks like you made the change to the documentation but forgot the main change to the card component template

**Comment by amrutadotorg** [comment]
Hi. I think it was done here #355

**Comment by lovasoa** [comment]
I see! Can you make the change in the other pull request, then? Closing this one.

**Comment by amrutadotorg** [comment]
Hi, please take a look at #365. I hope it is ok now.

**Pull request closed without merging**
