### PR TITLE
feat: open a new tab when clicking on the menu and submenu.

### PR DESCRIPTION
**Pull request by sijucj**
sample follows

```sql
select 
    'shell'                     as component,
    'SQLPage: SQL to web pages' as title,
    'database'                  as icon,
    '/'                         as link,  
    JSON('{"title":"Community","submenu":[{"link":"//github.com/lovasoa/sqlpage/issues","title":"Report a bug","icon":"bug","target":"__blank"}]}') as menu_item,
    JSON('{"title":"Report a bug","link":"//github.com/lovasoa/sqlpage/issues","target":"__blank"}') as menu_item,
    'boxed'                     as layout,
    'en-US'                     as language,
    'Go from SQL queries to web applications in an instant.' as description,
    'https://sql.datapage.app/sqlpage_social_preview.webp' as preview_image,
    'Poppins'                   as font,
    'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11/build/highlight.min.js' as javascript,
    'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11/build/languages/sql.min.js' as javascript,
    'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11/build/languages/handlebars.min.js' as javascript,
    'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11/build/languages/json.min.js' as javascript,
    '/highlightjs-launch.js'    as javascript,
    '/highlightjs-tabler-theme.css' as css,
    'Official [SQLPage](https://sql.datapage.app) documentation' as footer;
```

### CODE REVIEW

**Comment by lovasoa** [comment]
Great! We also need to document this new option

**Comment by lovasoa** [comment]
https://github.com/lovasoa/SQLpage/blob/9fd29619fc643934beb28f946cdd745402a9200c/examples/official-site/sqlpage/migrations/01_documentation.sql#L948

**Comment by sijucj** [comment]
> https://github.com/lovasoa/SQLpage/blob/9fd29619fc643934beb28f946cdd745402a9200c/examples/official-site/sqlpage/migrations/01_documentation.sql#L948

I have updated the file and pushed it

**Review by lovasoa — APPROVED** [review]

**Comment by lovasoa** [comment]
Thank you !

**Pull request merged**
