### PR TITLE
Shell navbar menu extension

### PR DESCRIPTION
**Pull request by pchemguy**
This modified "shell" component extends menu functionality (primarily adds support for icons in menu items and styling menu items as buttons). This pull request also contains a sample hybrid menu demo file menu_demo.sql.

### CODE REVIEW

**Comment by pchemguy** [comment]
I have updated this pull request to include all changes made in "Parse JSON menu_item for SQLite and skip blank items", so that this pull request could be merged without conflicts after the other one is accepted. Please take a look at the extended "shell" component and accept the pull request, if you think it is OK, or let me know of any issues.

**Comment by lovasoa** [comment]
Thanks  for the PR !

There are multiple things here.

I'm still not convinced by the looks of this

image

But I clearly see the interest of `fixed_top` for instance.

Can you open distinct pull requests ? This will make it easier to merge what can be merged now, and to discuss what still needs to be discussed.

**Comment by pchemguy** [comment]
To clarify, the three new PRs are just that (parts of the previous bigger PR).

**Comment by lovasoa** [comment]
Great, I already merged the sticky top menus. I'm closing this one in favor of the others, then

**Pull request closed without merging**
