### PR TITLE
 faster run_sql with shared database connection

### PR DESCRIPTION
**Pull request by lovasoa**
see https://github.com/lovasoa/SQLpage/issues/338

### CODE REVIEW

**Comment by lovasoa** [comment]
@vlasky @guspower : this ended up being a larger change than expected... Would any of you be available to test this on your applications before I release the change for everyone ? I would like to make sure the change does not have any unexpected consequences.

**Comment by guspower** [comment]
@lovasoa yes I can take it for a spin tomorrow and let you know.

**Comment by guspower** [comment]
FYI I cloned `better_run_sql_management` yesterday and ran the release build against a reasonable size app - no issues functionally. I was going to cook up a performance test to compare against the previous release but I see you've merged in so I'll hold off for now.

**Comment by lovasoa** [comment]
Great to hear it works. And I'd actually would be very interested in the numbers you get on your application in a performance test.

**Comment by guspower** [comment]
Me too! First I am going to set up a functional check using `spider` and then figure out how to run a perf test (which is always a pain :) ) I doubt I'll get one running this week due to workload, but when I do I will share.

**Pull request merged**
